version: '3.8'

services:
  db:
    image: postgres:15
    container_name: database-ycyw
    restart: unless-stopped
    environment:
      POSTGRES_USER: ycyw-user
      POSTGRES_PASSWORD: ycyw-passwd
      POSTGRES_DB: yourcaryourway_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data: