CREATE TYPE "car_category" AS ENUM (
    'city',
    'suv',
    'van',
    'sport',
    'electric'
    );

CREATE TYPE "car_model" AS ENUM (
    'Toyota Yaris',
    'Renault Clio',
    'Peugeot 208',
    'Tesla Model 3'
    );

CREATE TABLE "Threads" (
                           "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                           "userId" INTEGER NOT NULL,
                           "createdAt" TIMESTAMP NOT NULL,
                           "updatedAt" TIMESTAMP NOT NULL,
                           "title" VARCHAR(255) NOT NULL,
                           PRIMARY KEY("id")
);

CREATE TABLE "MessagesThreads" (
                                   "threadId" INTEGER NOT NULL,
                                   "messageId" INTEGER NOT NULL,
                                   PRIMARY KEY("threadId", "messageId")
);

CREATE TABLE "MessagesAsync" (
                                 "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                 "userId" INTEGER NOT NULL,
                                 "title" VARCHAR(255) NOT NULL,
                                 "content" TEXT NOT NULL,
                                 PRIMARY KEY("id")
);

CREATE TABLE "Users" (
                         "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                         "firstName" VARCHAR(255) NOT NULL,
                         "lastName" VARCHAR(255) NOT NULL,
                         "password" VARCHAR(255) NOT NULL,
                         "email" VARCHAR(255) NOT NULL UNIQUE,
                         "phone" VARCHAR(15),
                         "birthdate" DATE,
                         "stripeCustomerId" VARCHAR(255) NOT NULL,
                         "stripePaymentMethodId" VARCHAR(255) NOT NULL,
                         PRIMARY KEY("id")
);

CREATE TABLE "Messages" (
                            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                            "message" TEXT NOT NULL,
                            "createdAt" TIMESTAMP NOT NULL,
                            "updatedAt" TIMESTAMP NOT NULL,
                            PRIMARY KEY("id")
);

CREATE TABLE "Agencies" (
                            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                            "address" VARCHAR(255) NOT NULL,
                            "postalCode" VARCHAR(255) NOT NULL,
                            "city" VARCHAR(255) NOT NULL,
                            PRIMARY KEY("id")
);

CREATE TABLE "Cars" (
                        "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                        "agenceId" INTEGER NOT NULL,
                        "category" CAR_CATEGORY NOT NULL,
                        "modele" CAR_MODEL NOT NULL,
                        "immatriculation" VARCHAR(255) NOT NULL UNIQUE,
                        PRIMARY KEY("id")
);

CREATE TABLE "Reservation" (
                               "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                               "userId" INTEGER NOT NULL,
                               "agencyId" INTEGER NOT NULL,
                               "startDate" TIMESTAMP NOT NULL,
                               "endDate" TIMESTAMP NOT NULL,
                               "startCity" VARCHAR(255) NOT NULL,
                               "endCity" VARCHAR(255) NOT NULL,
                               "price" SMALLINT NOT NULL,
                               PRIMARY KEY("id")
);

CREATE TABLE "CarsReservations" (
                                    "carId" INTEGER NOT NULL,
                                    "reservationId" INTEGER NOT NULL,
                                    PRIMARY KEY("carId", "reservationId")
);

ALTER TABLE "MessagesThreads"
    ADD FOREIGN KEY("threadId") REFERENCES "Threads"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Threads"
    ADD FOREIGN KEY("userId") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "MessagesAsync"
    ADD FOREIGN KEY("userId") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "CarsReservations"
    ADD FOREIGN KEY("carId") REFERENCES "Cars"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "CarsReservations"
    ADD FOREIGN KEY("reservationId") REFERENCES "Reservation"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Reservation"
    ADD FOREIGN KEY("userId") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Cars"
    ADD FOREIGN KEY("agenceId") REFERENCES "Agencies"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "MessagesThreads"
    ADD FOREIGN KEY("messageId") REFERENCES "Messages"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Reservation"
    ADD FOREIGN KEY("agencyId") REFERENCES "Agencies"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;